### PR TITLE
Added DFS Traversal of Graph

### PR DESCRIPTION
**Pull request by ShaikSarfraj-tech**
Hi Sir, I have added the DFS Traversal of Graph. So, Kindly Accept it.
Thank you.

### CODE REVIEW

**Comment by MayankG514** [comment]
> Hi Sir, I have added the DFS Traversal of Graph. So, Kindly Accept it.
> Thank you.

Hii! 
https://ide.geeksforgeeks.org/WjtcXgqWYx
Your code doesn't run on this compiler. Kindly re run and verify! Thanks for contributing :)

**Comment by ShaikSarfraj-tech** [comment]
Hello Sir, It is Working. And we need to enter the input as the number of Vertices.
So, kindly look and Accept it.
Screenshot from 2020-10-15 12-52-49

**Comment by MayankG514** [comment]
> Hello Sir, It is Working. And we need to enter the input as the number of Vertices.
> So, kindly look and Accept it.
> Screenshot from 2020-10-15 12-52-49

Looks Great! Keep Contributing :)

**Comment by ShaikSarfraj-tech** [comment]
Thank you, Sir
Can I add one more Algorithm to this repository? Will you accept and it counts towards Hacktoberest2020.

**Comment by MayankG514** [comment]
> Thank you, Sir
> Can I add one more Algorithm to this repository? Will you accept and it counts towards Hacktoberest2020.

Surely, more than one PRs are welcome. Share this repo with your friends too :)
To be clear, I've created this repo with all the requirements for hactoberfest and following the instructions for the same. The rest depends on the hacktoberfest team wether or not consider PRs in this repo.

**Pull request merged**
